name: Build Container

on:
  push:
    branches:
      - main

  workflow_dispatch:
  
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:

      - name: Add Packer key
        run: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -

      - name: Add Packer repo
        run: sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

      - name: Install Packer
        run: sudo apt-get update && sudo apt-get install packer

      - name: Install Docker plugin for Packer
        run: sudo packer plugins install github.com/hashicorp/docker

      # - name: Install Docker plugin for Packer
      #   run: packer plugins install github.com/hashicorp/amazon

      - uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-1est-1
          role-duration-seconds: 1200
      
      - name: Packer build
        run: cd .build && sudo packer build cash4concepts.pkr.hcl
        env:
          AWS_DEFAULT_REGION: eu-west-1
